### ISSUE TITLE
Add more awesome web-development projects 

### ISSUE THREAD

**Issue by hanshulll** [hanshulll/WEB-DEVELOPMENT#19]
You can help to contribute by adding your awesome web-develoment projects folders in this repository.

**Comment by HimangsKalita** [comment]
In which directory do we have to push our project?

**Comment by hanshulll** [comment]
**@HimangsKalita 
You just have to add your project folder in this repository.
but as of now i am not sure that is this repo is being added in the hactoberfest 2021 or not**

**Comment by HimangsKalita** [comment]
oh alright
